# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('precio_por_unidad', models.FloatField()),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(blank=None, default=datetime.datetime(2017, 10, 16, 0, 14, 57, 694000), null=None)),
                ('fotografia', models.BinaryField(blank=True)),
                ('IDcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_producto.Categoria')),
            ],
        ),
    ]
