# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2017, 10, 16, 0, 16, 57, 161000), null=None),
        ),
    ]
