# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0002_auto_20171016_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2017, 10, 16, 0, 26, 18, 847000), null=None),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
